version: '3'
services:
  database:
    container_name: db
    restart: always
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: lms
      MYSQL_ROOT_PASSWORD: 123123

  java:
    image: lms
    depends_on:
      - database
    ports:
      - "7080:8080"